flower_order/urls.py
from django.urls import path

from .views import (
    BouquetListView,
    CatalogListView,
    Consultation,
    OrderView,
    OrderStep,
    Quiz,
    QuizStep,
    Result,
    Card,
    OrderStepRedirectView,
)


app_name = "flower_order"
payment_url = 'https://api.paybox.money/payment.php?pg_merchant_id=526740&pg_amount=200&pg_currency=RUB&pg_description=Футболка+с+принтом&pg_salt=kFQ4pYsAV1K531C0&pg_sig=26c83d710e86e916acffb80ea931a30e'

urlpatterns = [
    path('', BouquetListView.as_view(), name='start'),
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('catalog/all/', CatalogListView.as_view(), name='all_catalog'),
    path('consultation/', Consultation.as_view(), name='consultation'),
    path('order/', OrderView.as_view(), name='order'),
    # path('order-step/', OrderStep.as_view(), name='order_step'),
    path('order-step/', OrderStepRedirectView.as_view(url=payment_url), name='order_step'),
    path('quiz/', Quiz.as_view(), name='quiz'),
    path('quiz-step/', QuizStep.as_view(), name='quiz_step'),
    path('result/', Result.as_view(), name='result'),
    path('card/<int:pk>/', Card.as_view(), name='card'),
]

flower_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flower_order.urls')),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

flower_order/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField


class Category(models.Model):
    title = models.CharField(
        verbose_name='Название',
        db_index=True,
        max_length=200,
        unique=True,
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.title


class Bouquet(models.Model):
    title = models.CharField(
        verbose_name='Название',
        db_index=True,
        max_length=200,
        unique=True,
    )
    categories = models.ManyToManyField(
        Category,
        verbose_name='Категории',
        related_name='bouquets',
    )
    price = models.PositiveSmallIntegerField(
        verbose_name='Цена',
        default=1600,
    )
    image = models.FileField(
        verbose_name='Изображение',
        blank=True,
        null=True,
        upload_to='images/bouquets',
        validators=[FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])],
    )
    discription = models.TextField(
        verbose_name='Описание',
        blank=True,
        null=True,
    )
    structure = models.TextField(
        verbose_name='Состав',
        blank=True,
        null=True,
    )
    height = models.PositiveSmallIntegerField(
        verbose_name='Высота',
        default=30,
    )
    width = models.PositiveSmallIntegerField(
        verbose_name='Ширина',
        default=20,
    )

    class Meta:
        verbose_name = 'букет'
        verbose_name_plural = 'букеты'

    def __str__(self):
        return self.title


class Shop(models.Model):
    phonenumber = PhoneNumberField(
        verbose_name='Телефон',
        db_index=True,
        region='RU',
        unique=True,
    )
    address = models.CharField(
        verbose_name='Адрес',
        db_index=True,
        max_length=200,
        unique=True,
    )
    image = models.FileField(
        verbose_name='Изображение',
        blank=True,
        null=True,
        upload_to='images/shops',
        validators=[FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])],
    )
    latitude = models.DecimalField(
        verbose_name='Широта',
        decimal_places=6,
        default=59.940722,
        max_digits=8,
    )
    longitude = models.DecimalField(
        verbose_name='Долгота',
        decimal_places=6,
        default=30.396429,
        max_digits=8,
    )

    class Meta:
        verbose_name = 'магазин'
        verbose_name_plural = 'магазины'

    def __str__(self):
        return self.address


class Staff(models.Model):
    position_choices = [
        ('master', 'Мастер'),
        ('courier', 'Курьер'),
    ]

    phonenumber = PhoneNumberField(
        verbose_name='Телефон',
        db_index=True,
        region='RU',
        unique=True,
    )
    name = models.CharField(
        verbose_name='Имя',
        max_length=200,
    )
    surname = models.CharField(
        verbose_name='Фамилия',
        max_length=200,
    )
    position = models.CharField(
        verbose_name='Должность',
        choices=position_choices,
        max_length=200,
    )

    class Meta:
        verbose_name = 'сотрудник'
        verbose_name_plural = 'сотрудники'

    def __str__(self):
        return f'{self.get_position_display()}: {self.name} {self.phonenumber}'


class Client(models.Model):
    phonenumber = PhoneNumberField(
        verbose_name='Телефон',
        db_index=True,
        region='RU',
        unique=True,
    )
    name = models.CharField(
        verbose_name='Имя',
        max_length=200,
        blank=True,
        null=True,
    )
    surname = models.CharField(
        verbose_name='Фамилия',
        max_length=200,
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

    def __str__(self):
        return f'{self.name} {self.phonenumber}'


class Order(models.Model):
    service_choices = [
        ('consultation', 'Консультация'),
        ('delivery', 'Доставка'),
    ]
    status_choices = [
        ('1 not processed', 'Необработан'),
        ('2 collect', 'Собирается'),
        ('3 on way', 'В пути'),
        ('4 completed', 'Выполнен'),
    ]

    client = models.ForeignKey(
        Client,
        on_delete=models.CASCADE,
        related_name='orders',
        verbose_name='Клиент',
    )
    staff = models.ForeignKey(
        Staff,
        on_delete=models.SET_NULL,
        null=True,
        related_name='orders',
        verbose_name='сотрудник',
    )
    service = models.CharField(
        verbose_name='Статус',
        blank=True,
        choices=service_choices,
        max_length=15,
        null=True,
    )
    status = models.CharField(
        verbose_name='Статус',
        choices=status_choices,
        default='1 not processed',
        db_index=True,
        max_length=15,
    )
    address = models.CharField(
        verbose_name='Адрес доставки',
        blank=True,
        max_length=200,
        null=True,
    )
    delivery_at = models.DateTimeField(
        verbose_name='Когда доставить',
        default=timezone.now() + timezone.timedelta(1)
    )
    bouquets = models.ManyToManyField(
        Bouquet,
        verbose_name='Букеты',
        related_name='orders'
    )
    comment = models.CharField(
        verbose_name='Комментарий',
        max_length=100,
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'{self.get_service_display() } - {self.get_status_display() } - {self.client}'

flower_order/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, TemplateView, DetailView, RedirectView
from .models import Bouquet, Category, Shop, Client, Order
from django.db.models import Window, F
from django.db.models.functions import DenseRank, Random
import re


class ConsultationSendMixin:

    @staticmethod
    def verify_phone(tel):
        pattern = re.compile(r'^(\+7|7|8)?[\s\-]?\(?[489][0-9]{2}\)?[\s\-]?[0-9]{3}[\s\-]?[0-9]{2}[\s\-]?[0-9]{2}$')
        return bool(pattern.findall(tel))

    @staticmethod
    def normalize_phone(tel):
        return ''.join(['+7'] + [i for i in tel if i.isdigit()][-10:])

    def save_order_consultation(self):
        if self.request.GET:
            tel = self.request.GET.get('tel', '')
            if self.verify_phone(tel):
                first_name = self.request.GET.get('fname', '')
                tel = self.normalize_phone(tel)
                client, __ = Client.objects.get_or_create(phonenumber=tel, defaults={'name': first_name})
                Order.objects.create(client=client, service='consultation', comment='Заявка на консультацию')


class BouquetListView(ListView, ConsultationSendMixin):
    model = Bouquet
    queryset = Bouquet.objects.annotate(number=Window(expression=DenseRank(), order_by=[Random()]))[:3]
    context_object_name = 'bouquets'
    template_name = "flower_order/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shops'] = Shop.objects.all()
        self.save_order_consultation()
        return context


class CatalogListView(ListView, ConsultationSendMixin):
    model = Bouquet
    context_object_name = 'blocks'
    template_name = "flower_order/catalog.html"

    def get_queryset(self):
        item, blocks = [], []
        if self.request.GET.get('display') == 'more':
            bouquets = Bouquet.objects.annotate(number=Window(expression=DenseRank(), order_by=[F('pk').desc()]))
            all_row = len(bouquets) // 3
        else:
            bouquets = Bouquet.objects.annotate(number=Window(expression=DenseRank(), order_by=[Random()]))
            all_row = 2
        row_number = 0
        for bouquet in bouquets:
            item.append(bouquet)
            if bouquet.number % 3 == 0:
                blocks.append(item)
                item = []
                row_number += 1
            if row_number == all_row:
                break
        blocks.append(item)
        return blocks

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.save_order_consultation()
        if self.request.GET.get('display') == 'more':
            context['display'] = '1'
            context['button_text'] = 'Скрыть'
            context['block_name'] = 'Все букеты'
        else:
            context['display'] = 'more'
            context['button_text'] = 'Показать всё'
            context['block_name'] = 'Примеры букетов'
        return context


class Consultation(TemplateView, ConsultationSendMixin):
    template_name = "flower_order/consultation.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.save_order_consultation()
        return context


class OrderView(TemplateView, ConsultationSendMixin):
    template_name = "flower_order/order.html"

    def get_context_data(self, **kwargs):
        bouquet_pk = self.request.GET.get('bouquet', 0)
        context = super().get_context_data(**kwargs)
        context['bouquet_pk'] = bouquet_pk
        context['delivery_times'] = [
            'Как можно скорее',
            'с 10:00 до 12:00',
            'с 12:00 до 14:00',
            'с 14:00 до 16:00',
            'с 16:00 до 18:00',
            'с 18:00 до 20:00'
        ]
        self.save_order_consultation()

        if bouquet_pk and int(bouquet_pk):
            bouquet = Bouquet.objects.get(pk=bouquet_pk)
            context['price'] = f'{bouquet.price} ₽'

        return context


class OrderStep(TemplateView, ConsultationSendMixin):

    def get_context_data(self, **kwargs):
        self.template_name = "flower_order/order-step.html"
        context = super().get_context_data(**kwargs)
        if self.request.GET:
            tel = self.request.GET.get('tel', '')
            if not self.verify_phone(tel):
                self.template_name = "flower_order/order.html"
            else:
                first_name = self.request.GET.get('fname', '')
                address = self.request.GET.get('address', '')
                bouquet_pk = self.request.GET.get('bouquet', '0')
                order_time = self.request.GET.get('orderTime', '')
                tel = self.normalize_phone(tel)
                client, __ = Client.objects.get_or_create(phonenumber=tel, defaults={'name': first_name})
                order = Order.objects.create(client=client, address=address, comment=order_time, service='delivery')
                if bouquet_pk and int(bouquet_pk):
                    bouquet = Bouquet.objects.get(pk=bouquet_pk)
                    order.bouquets.add(bouquet)
                    context['price'] = f'{bouquet.price} ₽'
        # блок оплаты
        if self.request.GET.get('price', ''):
            self.template_name = "flower_order/order-step.html"
            card_num = self.request.GET.get('cardNum', '')
            card_month = self.request.GET.get('cardMm', '')
            card_year = self.request.GET.get('cardGg', '')
            card_name = self.request.GET.get('cardFname', '')
            card_cvc = self.request.GET.get('cardCvc', '')
            card_mail = self.request.GET.get('mail', '')
            price = int(self.request.GET.get('price', 0))
            print(card_name, card_month, card_year, card_cvc, price)
            #payment_send(payment_bot=settings.BOT, value=round(price, 0), chat_id=os.environ['TELEGRAM_ID']) #тестовая оплата через бота
        return context


class Quiz(ListView, ConsultationSendMixin):
    model = Category
    context_object_name = 'categories'
    template_name = "flower_order/quiz.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.save_order_consultation()
        return context


class QuizStep(TemplateView, ConsultationSendMixin):
    template_name = "flower_order/quiz-step.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.save_order_consultation()
        event = self.request.GET.get('event', '')
        category = get_object_or_404(Category, title=event)
        context['event'] = event
        price_range = list(category.bouquets.order_by('price'))
        max_price = round(price_range[-1].price, 0)
        min_price = round(price_range[0].price, 0)
        prices = [
            {'min': '0', 'max': f'{min_price + 100}', 'text': f'До {min_price + 100} руб'},
            {'min': f'{min_price + 100}', 'max': f'{max_price - 100}', 'text': f'{min_price + 100} - {max_price - 100} руб'},
            {'min': f'{max_price - 100}', 'max': 1000000, 'text': f'От {max_price - 100}'},
            {'min': 0, 'max': 1000000, 'text': 'Не имеет значения'}
        ]
        context['prices'] = prices
        return context


class Result(ListView, ConsultationSendMixin):
    template_name = "flower_order/result.html"
    context_object_name = 'bouquet'

    def get_queryset(self):
        self.save_order_consultation()
        if self.request.GET:
            event, min_price, max_price = self.request.GET.get('event', '').split('_')
            category = get_object_or_404(Category, title=event)
            return category.bouquets.filter(
                price__gt=int(min_price),
                price__lte=int(max_price)
            ).order_by('?').first()


class Card(DetailView, ConsultationSendMixin):
    template_name = "flower_order/card.html"
    model = Bouquet
    context_object_name = 'bouquet'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.save_order_consultation()
        return context


class OrderStepRedirectView(RedirectView, ConsultationSendMixin):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        tel = self.request.GET.get('tel', '')

        if not self.verify_phone(tel):
            self.url = self.request.META.get('HTTP_REFERER')
            return super().get_redirect_url(*args, **kwargs)
        else:
            first_name = self.request.GET.get('fname', '')
            address = self.request.GET.get('address', '')
            bouquet_pk = self.request.GET.get('bouquet', '0')
            order_time = self.request.GET.get('orderTime', '')
            tel = self.normalize_phone(tel)
            client, __ = Client.objects.get_or_create(phonenumber=tel, defaults={'name': first_name})
            order = Order.objects.create(client=client, address=address, comment=order_time, service='delivery')

            if bouquet_pk and int(bouquet_pk):
                bouquet = Bouquet.objects.get(pk=bouquet_pk)
                order.bouquets.add(bouquet)

        return super().get_redirect_url(*args, **kwargs)

flower_order/templates/flower_order/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flower Shop</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&family=Unbounded:wght@700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block add_style %}{% endblock %}
</head>
<body>
    <header id="header">
        <div class="container">
            <div class="header ficb">
                <a href="{% url 'flower_order:start' %}"><img src="{% static 'img/logo.svg' %}" alt="logo" class="logo"></a>
                <nav>
                    <ul class="menu ficc">
                        <li class="menu__item"><a href="{% url 'flower_order:catalog' %}" class="menu__item_link">Каталог</a></li>
                        <li class="menu__item"><a href="{% url 'flower_order:start' %}#recommended" class="menu__item_link">Рекомендации</a></li>
                        <li class="menu__item"><a href="{% url 'flower_order:start' %}#contacts" class="menu__item_link">Контакты</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
{% block body_contain %}{% endblock %}

<section id="consultation">
		<div class="container">
			<div class="consultation">
				<div class="title consultation__title">Оставьте заявку на консультацию</div>
				<form action="#" class="consultation__form">
					<input type="text" name="fname" class="consultation__form_input" placeholder="Введите Имя" required>
					<input type="text" name="tel" class="consultation__form_input" placeholder="+ 7 (999) 000 00 00" required>
					<button type="submit" class="consultation__form_btn">Отправить</button>
				</form>
			</div>
		</div>
	</section>

<footer id="footer">
    <div class="container">
        <div class="footer">
            <a href="{% url 'flower_order:start' %}"><img src="{% static 'img/logo.svg' %}" alt="logo" class="logo footer__logo"></a>
            <nav>
                <ul class="menu footer__menu ficc">
                    <li class="menu__item"><a href="{% url 'flower_order:catalog' %}" class="menu__item_link">Каталог</a></li>
                    <li class="menu__item"><a href="{% url 'flower_order:start' %}#recommended" class="menu__item_link">Рекомендации</a></li>
                    <li class="menu__item"><a href="{% url 'flower_order:start' %}#contacts" class="menu__item_link">Контакты</a></li>
                </ul>
            </nav>
            <hr class="line">
            </hr>
            <a href="#" class="footer__poli">Политика конфиденциальности</a>
            <p class="footer_cop">©️2022. FlowerShop. Все права защищены</p>
        </div>
    </div>
</footer>
</body>

</html>

flower_order/templates/flower_order/catalog.html
{% extends 'base.html' %}
{% load static %}

{% block add_style %}
<style type="text/css">
.recommended__block {
	display: flex;
    align-items: end;
	width: 398px;
	height: 400px;
	margin-right: 9px;
	color: #666;
	opacity: 0.8;
}
.recommended__block:link {text-decoration: none}
.recommended__block:visited {text-decoration: none}
.recommended__block:active {text-decoration: none}
.recommended__block:hover {
    font-size: 20px;
    font-weight: bold;
    color: #17CF97;
    opacity: 1;
    transform: scale(1.01);
    box-shadow:0 0 7px #00FF7F;
}
</style>
{% endblock %}

{% block body_contain %}
	<section id="catalog">
		<div class="container p100">
			<div class="catalog">
				<div class="title">{{ block_name }}</div>
				<div class="catalog__block">

					{% for block in blocks %}
						<div class="recommended__elems ficb recommended__elems_{% cycle 'first' 'sec' %}">
							{% for bouquet in block %}
								<a href="{% url 'flower_order:card' bouquet.pk %}" class="recommended__block" style="background: url('{{ bouquet.image.url }}') no-repeat center bottom / cover;">
									<div class="recommended__block_elems ficb">
										<span class="recommended__block_intro">{{ bouquet.title }}</span>
										<span class="recommended__block_price">{{ bouquet.price }} руб</span>
									</div>
								</a>
							{% endfor %}
						</div>
					{% endfor %}

					<form action="{% url 'flower_order:catalog' %}">
						<button class="btn largeBtn catalog__btn" name="display" value="{{ display }}">{{ button_text }}</button>
					</form>

				</div>
			</div>
		</div>
	</section>
{% endblock %}

flower_order/templates/flower_order/index.html
{% extends 'base.html' %}
{% load static %}

{% block add_style %}
<style type="text/css">
.recommended__block {
	display: flex;
    align-items: end;
	width: 398px;
	height: 400px;
	margin-right: 9px;
	color: #666;
	opacity: 1;
}
.recommended__block:link {text-decoration: none}
.recommended__block:visited {text-decoration: none}
.recommended__block:active {text-decoration: none}
.recommended__block:hover {
    font-size: 20px;
    font-weight: bold;
    color: #17CF97;
    opacity: 1;
    transform: scale(1.01);
    box-shadow:0 0 7px #00FF7F;
}
</style>
{% endblock %}

{% block body_contain %}
		<section id="banner">
			<div class="container">
				<div class="banner">
					<div class="banner__block">
						<h1 class="banner__title">Мастерская цветов</h1>
						<p class="banner__text">Подберем для вас букет за два шага, который идеально подойдет под вашу ситуацию</p>
						<a href="{% url 'flower_order:quiz' %}"><button class="btn banner__btn">Подобрать букет</button></a>
					</div>
					<img src="{% static 'img/bannerImg.png' %}" alt="banner Img" class="banner__img">
				</div>
			</div>
		</section>
	<section id="recommended">
		<div class="container">
			<div class="recommended p100">
				<div class="title">Рекомендуем</div>
				<div class="recommended__elems ficb">
				{% for bouquet in bouquets %}
					<a href="{% url 'flower_order:card' bouquet.pk %}" class="recommended__block" style="background: url('{{ bouquet.image.url }}') no-repeat center bottom / cover;">
						<div class="recommended__block_elems ficb">
							<span class="recommended__block_intro">{{ bouquet.title }}</span>
							<span class="recommended__block_price">{{ bouquet.price }} руб</span>
						</div>
					</a>
				{% endfor %}
				</div>
				<form action="{% url 'flower_order:catalog' %}">
				<button class="btn recommended__btn">Показать всю коллекцию</button>
				</form>

			</div>
		</div>
	</section>
	<section id="contacts">
		<div class="container">
			<div class="contacts">
				<div class="title">Как нас найти</div>
				<div class="contacts__elems ficb">
					<div class="contacts__block">
						{% for shop in shops %}
						<div class="contacts__block_item ficc">
							<div class="contacts__block_intro">{{ shop.address }}</div>
							<a href="tel:{{ shop.phonenumber }}" class="contacts__block_tel">{{ shop.phonenumber }}</a>
						</div>
						{% endfor %}
					</div>
					<img src="{% static 'img/contactsImg.jpg' %}" alt="contactsImg" class="contacts__img">
					<div class="contacts__map">
						<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ae7fa8f1f4d9486333bed8121193c663422c312713f8a1b1acd4532a641258273&amp;width=398&amp;height=316&amp;lang=ru_RU&amp;scroll=true"></script>
					</div>					
				</div>
				<form action="{% url 'flower_order:order' %}">
					<button class="btn contacts__btn">Заказать доставку</button>
				</form>
			</div>
		</div>
	</section>
{% endblock %}

flower_order/templates/flower_order/quiz-step.html
{% extends 'base.html' %}
{% load static %}
{% block body_contain %}
	<section id="quiz">
		<div class="container">
			<div class="quiz">
				<div class="quiz__back ">
					<a href="{% url 'flower_order:quiz' %}" class="quiz__back_link fic"><img src="{% static 'img/arrow-left.svg' %}" alt="arrow-left" class="arrowLeft">
					<span class="quiz__back_intro">Назад</span></a>
				</div>
				<div class="quiz__block">
					<h1 class="quiz__title">На какой бюджет рассчитываете?</h1>
					<div class="quiz__elems fic">
						<form action="{% url 'flower_order:result' %}">
							{% for price in prices %}
							<button class="quiz__elem" name="event" value="{{ event }}_{{ price.min }}_{{ price.max }}">{{ price.text }}</button>
<!--							<button class="quiz__elem" name="event" value="{{ event }}_2">1 000 - 5 000 руб</button>-->
<!--							<button class="quiz__elem" name="event" value="{{ event }}_3">от 5 000 руб</button>-->
<!--							<button class="quiz__elem" name="event" value="{{ event }}_4">Не имеет значения</button>-->
							{% endfor %}
						</form>

					</div>
					<div class="quiz__progress">
						<div class="quiz__progress_step">
							<span class="quiz__progress_num">2</span>
							<span class="quiz__progress_in"> шаг из </span>
							<span class="quiz__progress_num">2</span>
						</div>
						<div class="quiz__progress_line">
							<div class="quiz__progress_lineActive"></div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</section>
{% endblock %}

flower_order/templates/flower_order/result.html
{% extends 'base.html' %}
{% load static %}
{% block body_contain %}
	<section id="result">
		<div class="container">
			<div class="result p100">
				<div class="title">Мы подобрали специально для Вас</div>
				<div class="result__block ficb">
					<div class="result__elems">
						<div class="card__elems ">
							<span class="card__elems_intro">Описание:</span>
							<div class="card__items">
								<p class="card__items_text card__items_text__first">
									{{ bouquet.discription }}
								</p>
							</div>
						</div>
						<div class="card__elems ">
							<span class="card__elems_intro">Состав:</span>
							<div class="card__items">
								<p class="card__items_text card__items_text__first">
									{{ bouquet.structure }}
								</p>
								
							</div>
						</div>
					</div>
					<img src="{{ bouquet.image.url }}" alt="result Img" class="result__block_img">
					<div class="result__items">
						<div class="title result__items_title">{{ bouquet.title }}</div>
						<div class="result__items_price">{{ bouquet.price }} руб</div>
						<form action="{% url 'flower_order:order' %}">
							<button class="btn result__items_btn" name="bouquet" value="{{ bouquet.pk }}">Заказать букет</button>
						</form>

						<hr class="result__items_line" />
						<div class="result__items_intro">Хотите что-то более специальное?</div>
						<div class="result__items_block">
						<form action="{% url 'flower_order:catalog' %}">
							<button class="btn largeBtn result__items_block__btn">Смотреть всю коллекцию</button>
						</form>
						<form action="{% url 'flower_order:consultation' %}">
							<button class="btn largeBtn result__items_block__btn">Заказать консультацию</button>
						</form>
						</div>
					</div>
				</div>	
			</div>
		</div>
	</section>
	<section id="contacts">
		<div class="container">
			<div class="contacts">
				<div class="title">Как нас найти</div>
				<div class="contacts__elems ficb">
					<div class="contacts__block">
						<div class="contacts__block_item ficc">
							<div class="contacts__block_intro">ул. Пушкинская, 69</div>
							<a href="tel:89111744460" class="contacts__block_tel">8 (911) 17 44 460</a>
						</div>
						<div class="contacts__block_item ficc">
							<div class="contacts__block_intro">ул. Пушкинская, 69</div>
							<a href="tel:89111744460" class="contacts__block_tel">8 (911) 17 44 460</a>
						</div>
						<div class="contacts__block_item ficc">
							<div class="contacts__block_intro">ул. Пушкинская, 69</div>
							<a href="tel:89111744460" class="contacts__block_tel">8 (911) 17 44 460</a>
						</div>
					</div>
					<img src="{% static 'img/contactsImg.jpg' %}" alt="contactsImg" class="contacts__img">
					<div class="contacts__map">
						<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ae7fa8f1f4d9486333bed8121193c663422c312713f8a1b1acd4532a641258273&amp;width=398&amp;height=316&amp;lang=ru_RU&amp;scroll=true"></script>
					</div>					
				</div>
				<form action="{% url 'flower_order:order' %}">
					<button class="btn contacts__btn" name="bouquet" value="{{ bouquet.pk }}">Заказать доставку</button>
				</form>
			</div>
		</div>
	</section>
{% endblock %}